version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=votingsystem
    volumes:
      - voting_system_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'voting_system_redis_data:/bitnami/redis/data'

volumes:
  voting_system_pg_data:
  voting_system_redis_data:
